### ISSUE TITLE
Type errors in channels index.ts file

### ISSUE THREAD

**Issue by ALagoni97** [the-codegen-project/cli#103]
Should be a string:
![image](https://github.com/user-attachments/assets/8e64b9d5-01d3-478f-856c-7dcc60731f94)

Expecting an enum but got a string
![image](https://github.com/user-attachments/assets/5c996fa1-502d-4170-8a67-729b779894dd)

**Comment by jonaslagoni** [comment]
Parameter requirements:
- Validating values
- Isolated logic

**Comment by jonaslagoni** [comment]
Fixed in https://github.com/the-codegen-project/cli/pull/114
