### ISSUE TITLE
It seems like options passed to channels is not optional

### ISSUE THREAD

**Issue by ALagoni97** [the-codegen-project/cli#117]
![image](https://github.com/user-attachments/assets/51b287ed-ba93-4737-8d8c-52729c23085b)
Generated this error:
![image](https://github.com/user-attachments/assets/632c6328-43a0-4574-be49-c97316e52bb7)
Generated code:
![image](https://github.com/user-attachments/assets/303cc6b3-a714-4248-ba78-59465a9f8e3e)

It seems like we default to an empty object making the field optional. This however seems to not work properly.

**Comment by jonaslagoni** [comment]
Making options required
