### ISSUE TITLE
The connect fuction on the NATS class is returning Promise<void>

### ISSUE THREAD

**Issue by ALagoni97** [the-codegen-project/cli#150]
This code:
![image](https://github.com/user-attachments/assets/da4d1011-fffd-42f9-a460-5e777c075978)

Will generate a connect function where the return type is just void. It is not really feasible in the long / short term to not have better types. I suggest the following solution:
![image](https://github.com/user-attachments/assets/5dd1a3d3-1e9d-4e24-aa80-dce354f50df9)

**Comment by jonaslagoni** [comment]
Fixed in https://github.com/the-codegen-project/cli/pull/151, all the connect functions now return `{nc, js}`
