### ISSUE TITLE
When using client preset it seems to not respect my custom channel generator

### ISSUE THREAD

**Issue by ALagoni97** [the-codegen-project/cli#154]
Codegen:
```
import { TheCodegenConfiguration } from '@the-codegen-project/cli'
const config: TheCodegenConfiguration = {
	inputType: 'asyncapi',
	inputPath: '../../definitions/services/bundled/blackbox-api.asyncapi.json',
	language: 'typescript',
	generators: [
		{
			preset: 'client',
			outputPath: './src/__nats__/channels',
			language: 'typescript',
			protocols: ['nats'],
		},
		{
			preset: 'channels',
			outputPath: './src/__nats__/channels',
			language: 'typescript',
			protocols: ['nats'],
		},
```
Generates code:
![image](https://github.com/user-attachments/assets/454f8de7-0515-49b0-933f-8aa7eb64fc8d)

It generates both folders even though i have my own channels generated

**Comment by ALagoni97** [comment]
But when doing this:
```
const config: TheCodegenConfiguration = {
	inputType: 'asyncapi',
	inputPath: '../../definitions/services/bundled/blackbox-api.asyncapi.json',
	language: 'typescript',
	generators: [
		{
			preset: 'client',
			outputPath: './src/__nats__/channels',
			language: 'typescript',
			protocols: ['nats'],
		},
		{
			preset: 'channels',
			outputPath: './src/__nats__/channels',
			language: 'typescript',
			protocols: ['nats'],
		},
		{
			preset: 'payloads',
			outputPath: './src/__nats__/payloads',
			serializationType: 'json',
			language: 'typescript',
			enum: 'enum',
			map: 'record',
			useForJavaScript: true,
			rawPropertyNames: false,
		},
		{
			preset: 'parameters',
			language: 'typescript',
			outputPath: './src/__nats__/parameters',
			serializationType: 'json',
		},
	],
}
```
It works with just that folder, but are they required for that then? It feels like it should just take the outputPath from the client preset and use that as the outputPath for the rest

**Comment by jonaslagoni** [comment]
This is actually the intended behavior as of now. 

We can change the behavior to be use the `channels` preset `outputPath` as the baseline for the `outputPaths` of the rest. Would that make sense? 

If yes, what default relative paths should be used for the generators? :thinking:

**Comment by ALagoni97** [comment]
I think it would make sense to:
1. If the user has already defined a channels generator, we use that generator instead of making our own (I am guessing we are making our own or are we just overwriting the outputPath?) 
2. If the user has not defined a channels generator but defined a preset: 'client' generator, then we assume it's because the user wants us to do a default channels generator. Then use the outputPath the user has defined in preset: 'client' generator. 

That's my opinion anyway. We shouldn't force our default path anywhere unless absolutely sure.

**Comment by jonaslagoni** [comment]
So with;

```
		{
			preset: 'client',
			outputPath: './src/__nats__/channels',
			language: 'typescript',
			protocols: ['nats'],
		}
```
Do we assume the outputPath should be `src/__nats__/channels`, `src/__nats__/parameters`, and `src/__nats__/payloads`? 

And given;
```
		{
			preset: 'client',
			outputPath: './src/__nats__/channels',
			language: 'typescript',
			protocols: ['nats'],
		},
		{
			preset: 'channels',
			outputPath: './src/__nats__/channels',
			language: 'typescript',
			protocols: ['nats'],
		},
```
Do we assume the outputPath should be  `src/__nats__/parameters`, and `src/__nats__/payloads`?

**Comment by ALagoni97** [comment]
Yeah I think that makes sense

**Comment by jonaslagoni** [comment]
Slightly different output paths, but this way is future proof file still fixes the issue.
