### ISSUE TITLE
Add global import to root of the output folder

### ISSUE THREAD

**Issue by ALagoni97** [the-codegen-project/cli#81]
It would be nice if there was a global import ts file for typescript generator so all imports come from the same place. 

Currently my imports look like this:
`import { GeneratorTypes } from '../__codegen__/payloads/GeneratorTypes'`

It would be nice if it was just:
`import { GeneratorTypes } from '../__codegen__'`

**Comment by jonaslagoni** [comment]
Gonna be solved in https://github.com/the-codegen-project/cli/issues/82
