### ISSUE TITLE
Add possibility to also generate NatsClient

### ISSUE THREAD

**Issue by ALagoni97** [the-codegen-project/cli#82]
Normally my code looks like this:
`export const natsClient = new NatsAsyncApiClient()`
This is code also generated, but generated by another library. 
It's nice to have a generated NatsClient that we can use instead of having to install yet another library such as "nats" to connect to the nats server.

**Comment by jonaslagoni** [comment]
Not planned for now, but at some point a `client` generated class might make sense

**Comment by ALagoni97** [comment]
Going to bump this as we discussed to focus on this pattern.
