### ISSUE TITLE
CLI expects parameters for a channel that does not have it

### ISSUE THREAD

**Issue by ALagoni97** [the-codegen-project/cli#89]
Something like this:
```json
"channels": {
    "runs.command.forceGeneration": {
	    "description": "This force a generation with very basic information as the rest is fetched",
	    "publish": {
		    "summary": "Force a generation with specific information",
		    "operationId": "forceGeneration",
		    "message": {
			    "$ref": "#/components/messages/forceGeneration"
		    }
	    },
	    "bindings": {
		    "$ref": "./bindings.json#/components/channelBindings/ForceGeneration"
	    }
    },
}
```
Throws an error:
![image](https://github.com/user-attachments/assets/5ddba011-683b-42be-bf13-0a98b9b48824)

**Comment by jonaslagoni** [comment]
@all-contributors please add @ALagoni97 for bug, maintenance, projectManagement, review

**Comment by jonaslagoni** [comment]
@all-contributors please add @ALagoni97 for bug, maintenance, projectManagement, review

**Comment by jonaslagoni** [comment]
https://github.com/all-contributors please add @ALagoni97 for bug, maintenance, projectManagement, review
